# Generated by Django 4.1.1 on 2022-09-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='photos/banner')),
                ('description', models.TextField(blank=True, max_length=255)),
                ('is_selected', models.BooleanField(default=False)),
                ('status', models.CharField(default='Active', max_length=10)),
            ],
        ),
    ]
