# Generated by Django 4.1.1 on 2022-10-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_coupon_applied_product_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_off',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
