# Generated by Django 4.1.1 on 2022-10-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_product_off_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order_product',
            name='discount_price',
            field=models.FloatField(null=True),
        ),
    ]
